### ISSUE TITLE
too few arguments to function ‘embVector_subtract’

### ISSUE THREAD

**Issue by bianchifan** [Embroidermodder/Embroidermodder#312] opened 2023-03-07 12:05 UTC
/media/majo/Daten/git/Embroidermodder/src/objects.c:3162:17: error: too few arguments to function ‘embVector_subtract’
 3162 |         delta = embVector_subtract(global.center, global.point1);
      |                 ^~~~~~~~~~~~~~~~~~
In file included from /media/majo/Daten/git/Embroidermodder/src/embroidermodder.h:27,
                 from /media/majo/Daten/git/Embroidermodder/src/objects.c:16:

**Comment by robin-swift** [comment] 2023-03-07 22:21
This looks like you've not got the current libembroidery. If you remove the `build/` directory and rerun `build.sh` it should work.

**Comment by bianchifan** [comment] 2023-03-08 17:13
Hmm.. 2dys ago i made a complete new clone.
1 minago I did an actual pull -> 5 files changed.
Now I have a different isnan:
/media/majo/Daten/git/Embroidermodder/src/actuator.c:73:17: error: non-floating-point argument in call to function ‘__builtin_isnan’
   73 |             if (isnan(result[i].double_data)) {
      |                 ^~~~~
make[2]: *** [CMakeFiles/embroidermodder.dir/build.make:76: CMakeFiles/embroidermodder.dir/src/actuator.c.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:139: CMakeFiles/embroidermodder.dir/all] Fehler 2
make: *** [Makefile:136: all] Fehler 2

**Comment by robin-swift** [comment] 2023-03-08 19:07
My suspicion here is that this is libembroidery still causing trouble since `result[i].double_data` is now an `EmbReal` which, if the definition is missing, is an `int` by default. If your libembroidery is current then it's typedef-ed to `float`.

Libembroidery is a submodule that I've updated within the last 2 days so the new clone won't have caught it and `git pull` may not update submodules unless `git submodule update` is called.

That's why in `build.bat`/`build.sh` the necessary git commands are called.

If you still get an error on removing `build/` and running `build.sh` then something else is going on and I'll try reproducing the bug.

**Comment by robin-swift** [comment] 2024-03-01 23:29
This is based on an old version of libembroidery and I can't reproduce the bug. I'm closing as fixed.

**Closed by robin-swift** 2024-03-01 23:29 UTC
Labels: bug, bitesized
